# Generated by Django 4.1.7 on 2023-03-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(null=True)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
            ],
        ),
    ]
